import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-app-blog',
  templateUrl: './app-blog.component.html',
  styleUrls: ['./app-blog.component.css']
})
export class AppBlogComponent implements OnInit {

  constructor() { }

  blogimg: any = '../../../assets/images/blog/blog.jpg';
  blogcontent: any = `Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, provident corrupti? Soluta deleniti eveniet
  dolorem ducimus vitae? Adipisci culpa amet earum molestias impedit. Fuga animi aliquid molestiae eligendi. Earum
  odio veritatis sint mollitia labore ipsam tenetur cum vitae, atque suscipit rem, corrupti obcaecati ullam nulla,
  sunt doloribus tempore fugiat quibusdam!`;

  posts: any[] = [
    { title: 'charminar', content: 'Charminar is really a beautiful monument built in 1500 century by the mughul rulers.it has 4 identical pillars beautifully constructed.It is located in old city n I was mesmerised seeing that giant monument.My 2 eyes were not enough to see such a beauty.There were many bangle shops near by Charminar.I n friends bought a dozen of bangles.Charminar is one of the monument which signifies Mughals in Hyderabad.We didnt go up of Charminar as they closed the entry as many people feel n lost their lives.We really had a lot of fun. Charmianr is the centre of attraction of Hyderabad.This monument is to be visited by everyone atleast once in their lifetime. We came back safely after our journey.',src:'../../../assets/images/blog/charminar.jpeg', by:'HR Team',on:'10/12/20'},
    { title: 'Tirumala', content: 'The purpose of Tirupati Tourism is the belief that Tirupati Balaji shall shower His divine blessings on His worshippers. Tirupati Temple is not just a holy destination but a combination of many surprises. Tirupati temple receives donations from various sources. The Supreme Lord’s sacred power brings visitors in huge numbers, who hope to witness His Grace.',src:'../../../assets/images/blog/thirumula.jpeg', by:'HR Team',on:'10/12/20' },
    { title: 'Golden Temple', content: 'The Golden Temple is totally encased in gold. At night, thousands of lights shine onto the exterior of the gold to create a dazzling appearance. In front of it, there is a massive man made shallow pond that reflects the lights. The effect of the gold, the lights and the reflection of the gold and the lights onto the pond, is absolutely captivating. Everyone who enters the Golden Temple must cover their head. Although the Golden Temple is an exceptionally important religious site for Sikhs, the atmosphere at the Golden Temple was joyful and celebratory. People talked, children played, and everyone was taking photos of themselves and each other.',src:'../../../assets/images/blog/goldentemple.jpeg', by:'HR Team',on:'10/12/20' },
    { title:'Thar Desert', content:'The desert is not empty as you might imagine it to be. There are plenty of animals and plant-life that you will see while exploring the Thar.This desert is a fine choice if you are one who is keen on understanding the local flora and fauna of the land and also curious in experiencing their village life. It is a great way to witness the local life of the people who live in this tough topography.The only mode of transport these villagers use is camels. However, this growing tourist spot also has jeep safari, for those who aren’t comfortable riding a camel.',src:'../../../assets/images/blog/thar.jpeg', by:'HR Team',on:'10/12/20'},
    { title: 'Varanasi', content: 'The Experience Varanasi tour is an awesome to connect the tourist with the city. It aims to acclimatize the Guest with the local culture of Varanasi. The tours will showcase not just the heritage monuments but also the city’s culture, cuisine, craft and life of the local people through the narrow lanes of Varanasi. We have various day tours suited to all kinds of Travelers coming to the city.', src:'../../../assets/images/blog/varanasi.jpeg', by:'HR Team',on:'10/12/20' },
    { title: 'Bangalore', content: 'There are countless things that I experienced in Banglore. Banglore has been blessed by the weather Gods. As i relocated recently, I cannot really comment on the old Bangalore but sincerely believe that it once was a great city.There are still breathers that Bangalore provides with its good educational institutes, infinite restaurants and pubs, big beautiful places like Indira Nagar and jaya Nagar, some amazing cafes and recreational centres.', src:'../../../assets/images/blog/banglore.jpeg', by:'HR Team',on:'10/12/20' },  
    { title: 'Tajmahal', content: 'Standing alone inside the Taj Mahal was a silent, peaceful, and moving experience. It took a second before it hit me—I could take a photo without another person in it—and so I did. ... We moved quickly to enter the Taj Mahal before the crowds, to allow us the rare opportunity to hear the wind and echo of its whistle.The day of the visit I had to go by taxi to a parking lot, where I procured my entry ticket and from where the rickety charming rickshaw took me to the entrance of the Taj Mahal. I felt my excitement grow as I approached the mausoleum.The front gate is simple and doesnt give the slightest of hint of what lies behind.', src:'../../../assets/images/blog/tajmahal.jpeg', by:'HR Team',on:'10/12/20' },
    { title: 'Shimla', content: 'It was a wonderful experience when I visited Shimla for the first time. It was a peak winters in Shimla and I happened to be placed in Delhi in my Job. Initially, I had shown some resistance to my Boss who had directed me to go on duty . This is because of peak winter season in January . Believe me when I stayed in Shimla for a couple of days , winters were all forgotton. Pollution free enviornment in Shimla, healthy food, calm and serene atmosphere made my stay so attractive that I fell in love with the place.Early morning you could see clouds at your feet and touching your palm.Tall trees and pony rides added beauty to the place.', src:'../../../assets/images/blog/shimla.jpeg', by:'HR Team',on:'10/12/20' },
    { title: 'Goa', content: 'The first thing I loved about Goa was the relaxed and laidback vibe that the place gave. You have the freedom to be yourself and forget all your tensions. The beaches in Goa are very beautiful and you will never feel like leaving the beach. The best beaches are Sequerim Beach and Miramar beach which are away from hustle bustle of Baga and Calangute. The sunset at miramar beach is mesmerizing. The churches are beautiful and very peaceful. In my opinion, Goa tourism is altogether a different product in winters/summers and monsoon. Although you cannot enjoy water sports during monsoon yet when it rains, the lush greenery glitters and its blissful to travel around Goa during this time.', src:'../../../assets/images/blog/goa.jpeg', by:'HR Team',on:'10/12/20' },
    { title: 'Kanyakumari', content: 'Kanyakumari is also one of the most beautiful place.Kanyakumari is the southernmost tip of mainland India and is surrounded by three water bodies. Bay of Bengal towards east, Indian Ocean in south and Arabian Sea in west. I think it is the only place to see sun rise and sun set in water bodies in India. Kanyakumari town is named after the goddess Kanyakumari amman, a popular deity of the area. Legend has it that the goddess Parvathi in one of her incarnation as devi Kanya did penance on one of the rock of this land’s end to obtain the hand of lord Siva.', src:'../../../assets/images/blog/kanyakumari.jpeg', by:'HR Team',on:'10/12/20' },
    { title: 'Nainital', content: 'Nainital is one of the most beautiful and visited places in the state of Uttarakhand.Nainital is located at an altitude of approximately 2084 m above sea level.Nainital is covered with beautiful mountains with Nainital Lake in between, which is the main attraction for Tourists.Its Climate which is favorable all year round makes it the perfect Tourist spot for everyone around.The Nainital lake is covered from many attractions around, such as Naina Devi Temple and the Tibetan market with multiple food shops.It is also considered as one of the most Budget-friendly and famous Tourist spots when it comes to Hill stations.', src:'../../../assets/images/blog/naintal.jpeg', by:'HR Team',on:'10/12/20' },
    { title: 'Ooty', content: 'Ooty is blessed with a wide wealth of natural beauty.  The beautiful valleys covered in lush green forests provide enough opportunities for tourists to take part in some form of trekking. It happens to be a very popular activity in this region and adventure enthusiasts visitors make sure to sign up for it in the course of their visit to Ooty. Set off in search of some of the exciting natural assets and gain some riches in the form of some experience that is unique to this land. Come and fall in love with trekking all over again here in Ooty.', src:'../../../assets/images/blog/ooty.jpeg', by:'HR Team',on:'10/12/20' }];

    ngOnInit() {
  }

}
